// frontend/src/components/cassandragrpc/StaticResultsSection.tsx
import React from 'react';
import cassandraGrpcResults from '../../data/staticResults/cassandraGrpcResults.json';
import { MetricCard } from '../shared/MetricCard';
import { ConfusionMatrixTable } from './ConfusionMatrixTable';
import { ClipboardCheck, Target } from 'lucide-react';

interface StaticResults {
  available: boolean;
  datasetSize?: number;
  modelType?: string;
  trainingTimeSeconds?: number;
  inferenceLatencyMs?: number;
  accuracy?: number;
  macroPrecision?: number;
  macroRecall?: number;
  macroF1?: number;
  topClasses?: { topicId: number; topicName: string; support: number }[];
  confusionMatrix?: { trueTopicId: number; predictedTopicId: number; count: number }[];
  examplePrediction?: { inputText: string; topicName: string; confidence: number };
  note: string;
}

const data = cassandraGrpcResults as unknown as StaticResults;

export const StaticResultsSection: React.FC = () => {
  return (
    <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 space-y-5">
      <div className="flex items-center gap-2 text-cyan-400 text-xs font-mono font-semibold uppercase tracking-wider">
        <ClipboardCheck className="w-4 h-4" />
        <span>Results</span>
      </div>
      <h2 className="text-xl font-bold text-white tracking-tight">Real Model Results</h2>

      {!data.available ? (
        <p className="text-sm text-slate-500">
          Not available -- this snapshot is generated by running{' '}
          <code className="text-slate-400">backend/scripts/generate_static_results.py</code> after a real
          training run has completed. {data.note}
        </p>
      ) : (
        <>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
            <MetricCard label="Dataset Size" value={data.datasetSize!.toLocaleString()} icon={Target} color="text-cyan-300" />
            <MetricCard label="Model" value={data.modelType!} icon={Target} color="text-cyan-300" />
            <MetricCard label="Training Time" value={`${data.trainingTimeSeconds!.toFixed(1)}s`} icon={Target} color="text-cyan-300" />
            <MetricCard label="Inference Latency" value={`${data.inferenceLatencyMs!.toFixed(1)}ms`} icon={Target} color="text-cyan-300" />
            <MetricCard label="Accuracy" value={`${(data.accuracy! * 100).toFixed(1)}%`} icon={Target} color="text-cyan-300" />
            <MetricCard label="Macro Precision" value={data.macroPrecision!.toFixed(3)} icon={Target} color="text-cyan-300" />
            <MetricCard label="Macro Recall" value={data.macroRecall!.toFixed(3)} icon={Target} color="text-cyan-300" />
            <MetricCard label="Macro F1" value={data.macroF1!.toFixed(3)} icon={Target} color="text-cyan-300" />
          </div>
          <div>
            <h3 className="text-sm font-bold text-slate-100 mb-2">Confusion Matrix (top classes by support)</h3>
            <ConfusionMatrixTable topClasses={data.topClasses!} confusionMatrix={data.confusionMatrix!} />
          </div>
          {data.examplePrediction && (
            <div className="rounded-xl bg-slate-950 border border-slate-800 p-4">
              <div className="text-[10px] text-slate-500 font-mono uppercase">Example prediction</div>
              <p className="text-sm text-slate-300 italic">"{data.examplePrediction.inputText}"</p>
              <p className="text-sm text-cyan-300 font-bold mt-1">
                {data.examplePrediction.topicName} ({(data.examplePrediction.confidence * 100).toFixed(1)}%)
              </p>
            </div>
          )}
          <p className="text-xs text-slate-400 border-t border-slate-800 pt-4">{data.note}</p>
        </>
      )}
    </div>
  );
};
