# UNVERIFIED: see cassandra-deployment.yaml.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-grpc-ml-cassandra-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
